// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Every endpoint answers with this envelope.
 */
export type ApiError = { 
/**
 * Stable machine-readable code, e.g. `invite_invalid`, `version_too_old`.
 */
code: string, message: string, };
