// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A voice channel. Its id is the LiveKit room name.
 */
export type Channel = { id: string, name: string, position: number, 
/**
 * Media server the channel is currently assigned to (changes on failover).
 */
serverId: string, };
