// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sent on login so the control plane can enforce the minimum version.
 */
export type ClientInfo = { appVersion: string, protocolVersion: number, platform: string, };
