// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from "./Settings";
import type { TrackKind } from "./TrackKind";
import type { TransmitMode } from "./TransmitMode";

/**
 * UI -> engine.
 */
export type Command = { "type": "setInputDevice", id: string | null, } | { "type": "setOutputDevice", id: string | null, } | { "type": "setTransmitMode", mode: TransmitMode, } | { "type": "setMuted", muted: boolean, } | { "type": "setDeafened", deafened: boolean, } | { "type": "setPeerVolume", identity: string, track: TrackKind, gainDb: number, } | { "type": "setPeerMuted", identity: string, track: TrackKind, muted: boolean, } | { "type": "applySettings", settings: Settings, } | { "type": "join", url: string, token: string, } | { "type": "leave" } | { "type": "refreshDevices" } | { "type": "resync" };
