// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompressorSettings = { enabled: boolean, thresholdDb: number, ratio: number, attackMs: number, releaseMs: number, makeupDb: number, };
