// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceStats = { name: string, sampleRate: number, channels: number, 
/**
 * Largest callback buffer seen, in frames — the effective device buffer.
 */
callbackFrames: number, 
/**
 * Capture: samples lost because the engine did not keep up. Playout: times a
 * speaker's buffer ran dry.
 */
xruns: number, };
