// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioDevice } from "./AudioDevice";
import type { ConnectionState } from "./ConnectionState";
import type { LogEntry } from "./LogEntry";
import type { Participant } from "./Participant";
import type { PeerLevel } from "./PeerLevel";
import type { Stats } from "./Stats";

/**
 * Engine -> UI.
 */
export type Event = { "type": "ready", protocolVersion: number, } | { "type": "devices", inputs: Array<AudioDevice>, outputs: Array<AudioDevice>, } | { "type": "levels", inputDb: number, gateOpen: boolean, peers: Array<PeerLevel>, } | { "type": "connection", state: ConnectionState, } | { "type": "error", message: string, } | { "type": "joined", room: string, identity: string, } | { "type": "participants", participants: Array<Participant>, } | { "type": "stats", stats: Stats, } | { "type": "log", entry: LogEntry, };
