// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioDevice } from "./AudioDevice";
import type { ConnectionState } from "./ConnectionState";
import type { PeerLevel } from "./PeerLevel";

/**
 * Engine -> UI.
 */
export type Event = { "type": "ready", protocolVersion: number, } | { "type": "devices", inputs: Array<AudioDevice>, outputs: Array<AudioDevice>, } | { "type": "levels", inputDb: number, gateOpen: boolean, peers: Array<PeerLevel>, } | { "type": "connection", state: ConnectionState, } | { "type": "error", message: string, };
