// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a person needs to join a voice room: where the media server is and a token for it.
 *
 * Until the control plane hands out a [`VoiceToken`] per login (S6), an invite is one line
 * of text (`cargo xtask livekit token`) that is pasted into the client. The text form is
 * `yappa1.` followed by the base64url of the JSON — made to survive a chat window, not to
 * hide anything: whoever has the text can join.
 */
export type Invite = { 
/**
 * `wss://…` (or `ws://localhost:7880` in development).
 */
url: string, token: string, };
