// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel";

export type LogEntry = { 
/**
 * Milliseconds since the Unix epoch.
 */
timeMs: number, level: LogLevel, 
/**
 * Where it came from, e.g. `transport::livekit`.
 */
target: string, message: string, };
