// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * From the transport's WebRTC statistics. "Recent" values cover the time since the
 * previous snapshot, the others are totals for this connection.
 */
export type NetworkStats = { 
/**
 * Round trip to the media server (ICE connectivity checks).
 */
rttMs: number, sendCodec: string, sendKbpsRecent: number, packetsSent: number, 
/**
 * Share of our packets the server reported missing, 0..100.
 */
uplinkLossPercent: number, packetsReceived: number, packetsLost: number, lossPercentRecent: number, jitterMs: number, 
/**
 * Mean time a sample waited in the jitter buffer.
 */
jitterBufferMs: number, 
/**
 * Share of played samples the decoder had to invent — what loss sounds like.
 */
concealedPercentRecent: number, concealedPercentTotal: number, };
