// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who sits where; pushed to clients, built from LiveKit webhooks + heartbeats.
 */
export type Presence = { channelId: string, userIds: Array<string>, };
