// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientInfo } from "./ClientInfo";

/**
 * First login: an invite link carries the code.
 */
export type RedeemInviteRequest = { code: string, displayName: string, client: ClientInfo, };
