// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type Session = { user: User, 
/**
 * Bearer token for later requests; kept in the OS keychain by the client.
 */
sessionToken: string, };
