// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressorSettings } from "./CompressorSettings";
import type { DenoiserKind } from "./DenoiserKind";
import type { EqBand } from "./EqBand";
import type { TransmitMode } from "./TransmitMode";

/**
 * Everything the user can set. Simple and pro view both read and write this.
 */
export type Settings = { version: number, inputDevice: string | null, outputDevice: string | null, transmitMode: TransmitMode, 
/**
 * Voice activation threshold, dBFS.
 */
vadThresholdDb: number, vadHoldMs: number, denoiser: DenoiserKind, highPassHz: number, eq: Array<EqBand>, compressor: CompressorSettings, 
/**
 * Voice track bitrate; the baseline asks for 64–96 kbps with RED, no DTX.
 */
voiceBitrateKbps: number, theme: string, };
