// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceStats } from "./DeviceStats";
import type { NetworkStats } from "./NetworkStats";

/**
 * One snapshot of everything worth watching while a call runs. `None` = not known (yet).
 */
export type Stats = { network: NetworkStats | null, capture: DeviceStats | null, playout: DeviceStats | null, 
/**
 * Longest gap between two 10 ms blocks handed to the transport since the last
 * snapshot — far above 10 means the send side stalled.
 */
sendIntervalMaxMs: number, 
/**
 * Capture blocks thrown away because a backlog had built up (total).
 */
sendBlocksDropped: number, 
/**
 * Received frames thrown away because a speaker's playout buffer was full (total).
 */
playoutFramesDropped: number, 
/**
 * Times playout jumped forward because a speaker's buffer ran over — their clock is
 * faster than our output device, or playout stalled (total).
 */
playoutSkips: number, };
