// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three published tracks per participant (see planning doc, "Quellen und Tracks").
 */
export type TrackKind = "voice" | "music" | "soundboard";
