// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Long-lived (≈ one gaming evening) so reconnects survive a control-plane outage.
 */
export type VoiceToken = { wsUrl: string, token: string, 
/**
 * RFC 3339.
 */
expiresAt: string, };
