//! Design tokens -> CSS variables. A theme is a file, not code (planning doc, "UI-Prinzipien").
//!
//! `ui-tokens/base.json`        flat map: spacing, radii, fonts      -> `--<key>` on :root
//! `ui-tokens/themes/<id>.json` `{ "name", "colors": { key: value } }` -> `--color-<key>`
//! The theme `dark` is the default (:root); every theme also gets `:root[data-theme="<id>"]`.

use serde_json::{Map, Value};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

const DEFAULT_THEME: &str = "dark";
const OUT: &str = "apps/desktop/src/lib/tokens.css";

pub fn generate(root: &Path) -> Result<(), String> {
    let dir = root.join("ui-tokens");
    let base = read_object(&dir.join("base.json"))?;

    let mut themes = Vec::new();
    let entries = fs::read_dir(dir.join("themes")).map_err(|e| format!("ui-tokens/themes: {e}"))?;
    for entry in entries {
        let path = entry.map_err(|e| e.to_string())?.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let id = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default()
            .to_string();
        let theme = read_object(&path)?;
        let colors = theme
            .get("colors")
            .and_then(Value::as_object)
            .ok_or_else(|| format!("{}: missing \"colors\" object", path.display()))?
            .clone();
        themes.push((id, colors));
    }
    themes.sort_by(|a, b| a.0.cmp(&b.0));
    let default = themes
        .iter()
        .find(|(id, _)| id == DEFAULT_THEME)
        .ok_or_else(|| format!("ui-tokens/themes/{DEFAULT_THEME}.json is required"))?;

    let mut css = String::from(
        "/* generated by `cargo xtask tokens` from ui-tokens/ — do not edit */\n:root {\n",
    );
    vars(&mut css, "", &base)?;
    vars(&mut css, "color-", &default.1)?;
    css.push_str("}\n");
    for (id, colors) in &themes {
        let _ = writeln!(css, "\n:root[data-theme=\"{id}\"] {{");
        vars(&mut css, "color-", colors)?;
        css.push_str("}\n");
    }

    let out = root.join(OUT);
    if fs::read_to_string(&out).ok().as_deref() != Some(css.as_str()) {
        fs::write(&out, css).map_err(|e| format!("{OUT}: {e}"))?;
        println!("wrote {OUT}");
    }
    Ok(())
}

fn read_object(path: &Path) -> Result<Map<String, Value>, String> {
    let text = fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    match serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))? {
        Value::Object(map) => Ok(map),
        _ => Err(format!("{}: expected an object", path.display())),
    }
}

fn vars(css: &mut String, prefix: &str, map: &Map<String, Value>) -> Result<(), String> {
    for (key, value) in map {
        let value = match value {
            Value::String(s) => s.clone(),
            Value::Number(n) => n.to_string(),
            other => return Err(format!("token {key}: unsupported value {other}")),
        };
        let _ = writeln!(css, "  --{prefix}{key}: {value};");
    }
    Ok(())
}
